### ISSUE TITLE
Release latest version to pypi

### ISSUE THREAD

**Issue by tuxtitlan** [raphaelm/django-scopes#25]
Latest version on pypi was released on June 13, 2019, current master has support for more recent versions of Django and Python, please release a new version that can be installed via pypi. Thanks.

**Comment by KyeRussell** [comment]
For anyone that comes across this: there doesn't seem to be any material changes between 53633943e31253f84f97cccf0a84c9ffb5876653 (current `master`) and tag `1.2.0`. It seems to all be related to testing and expanding on documentation. Not keeping pypi updated is a bit of a generally bad indication, but at the time of writing this comment, it doesn't appear to have any material effect.

**Comment by raphaelm** [comment]
Correct, there was no code change since the last release. The current release on PyPI also supports all current Django and Python versions, the commit message is just confusing. All that current master does is add **CI testing** for new Django and Python versions and extending the README.

I do not see the point of doing a release for a few added notes in the README.

We're running the current PyPI release in production on a large site with Django 3.2 and Python 3.8, works fine.

There are also no known bugs in this library, just things that it doesn't support yet and we do not spend time on since we don't need them.
